// Énumérations basées sur le backend mima

export enum AbsenceType {
    SICK_LEAVE = 'SICK_LEAVE',
    ANNUAL_LEAVE = 'ANNUAL_LEAVE',
    MATERNITY_LEAVE = 'MATERNITY_LEAVE',
    PATERNITY_LEAVE = 'PATERNITY_LEAVE',
    UNPAID_LEAVE = 'UNPAID_LEAVE',
    SPECIAL_LEAVE = 'SPECIAL_LEAVE',
    TRAINING = 'TRAINING',
    FAMILY_EMERGENCY = 'FAMILY_EMERGENCY'
}

export enum AbsenceStatus {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED'
}

// Statut des marins
export enum MarinerStatus {
    DISPONIBLE = 'DISPONIBLE',
    EN_MER = 'EN_MER',
    EN_GARDE = 'EN_GARDE',
    PERMISSION = 'PERMISSION',
    ABSENT = 'ABSENT',
    EN_FORMATION = 'EN_FORMATION',
    INDISPONIBLE = 'INDISPONIBLE'
}

// Grades maritimes
export enum MaritimeRank {
    CAPITAINE = 'CAPITAINE',
    COMMANDANT = 'COMMANDANT',
    LIEUTENANT = 'LIEUTENANT',
    ENSEIGNE = 'ENSEIGNE',
    MAITRE_PRINCIPAL = 'MAITRE_PRINCIPAL',
    PREMIER_MAITRE = 'PREMIER_MAITRE',
    MAITRE = 'MAITRE',
    SECOND_MAITRE = 'SECOND_MAITRE',
    QUARTIER_MAITRE_1ERE_CLASSE = 'QUARTIER_MAITRE_1ERE_CLASSE',
    QUARTIER_MAITRE_2EME_CLASSE = 'QUARTIER_MAITRE_2EME_CLASSE',
    MATELOT_BREVETE = 'MATELOT_BREVETE',
    MATELOT = 'MATELOT'
}

// Spécialités maritimes
export enum MaritimeSpecialty {
    NAVIGATION = 'NAVIGATION',
    MECANIQUE = 'MECANIQUE',
    COMMUNICATION = 'COMMUNICATION',
    ARMEMENT = 'ARMEMENT',
    ELECTRONIQUE = 'ELECTRONIQUE',
    SECURITE = 'SECURITE',
    PLONGEE = 'PLONGEE',
    AVIATION = 'AVIATION',
    SANTE = 'SANTE',
    CUISINE = 'CUISINE',
    ADMINISTRATION = 'ADMINISTRATION',
    LOGISTIQUE = 'LOGISTIQUE',
    ENERGIE = 'ENERGIE',
    DETECTION = 'DETECTION'
}

// Types de navires
export enum VesselType {
    FREGATE = 'FREGATE',
    CORVETTE = 'CORVETTE',
    PATROUILLEUR = 'PATROUILLEUR',
    SOUS_MARIN = 'SOUS_MARIN',
    PORTE_AVIONS = 'PORTE_AVIONS',
    BATIMENT_AMPHIBIE = 'BATIMENT_AMPHIBIE',
    RAVITAILLEUR = 'RAVITAILLEUR',
    DRAGUEUR = 'DRAGUEUR',
    REMORQUEUR = 'REMORQUEUR',
    VEDETTE = 'VEDETTE',
    NAVIRE_ECOLE = 'NAVIRE_ECOLE'
}

// Ancienne énumération (conservée pour compatibilité)
export enum AgentStatus {
    AVAILABLE = 'AVAILABLE',
    ON_MISSION = 'ON_MISSION',
    ON_DUTY = 'ON_DUTY',
    RESTING = 'RESTING',
    ABSENT = 'ABSENT'
}

export enum MissionStatus {
    PLANNED = 'PLANNED',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED'
}

export enum DutyType {
    WATCH = 'WATCH',
    BRIDGE_WATCH = 'BRIDGE_WATCH',
    ENGINE_WATCH = 'ENGINE_WATCH',
    ANCHOR_WATCH = 'ANCHOR_WATCH',
    PORT_WATCH = 'PORT_WATCH',
    STANDBY = 'STANDBY'
}

export enum DutyStatus {
    PLANNED = 'PLANNED',
    ACTIVE = 'ACTIVE',
    COMPLETED = 'COMPLETED',
    REPLACED = 'REPLACED',
    CANCELLED = 'CANCELLED'
}

export enum UnitType {
    SHIP = 'SHIP',
    BASE = 'BASE',
    SERVICE = 'SERVICE'
}

export enum UnitStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}

export enum AlertStatus {
    NEW = 'NEW',
    RESOLVED = 'RESOLVED'
}

export enum ActionType {
    CREATE = 'CREATE',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
    VALIDATE = 'VALIDATE'
}

// System 3 - Maritime/Commercial Ships Enums

export enum NavalVesselType {
    PHM = 'PHM',
    VDT_RAPIDE = 'VDT_RAPIDE',
    VDT_COTIERE = 'VDT_COTIERE',
    VDT = 'VDT',
    EMB_RAPIDE = 'EMB_RAPIDE',
    EMB_RADE = 'EMB_RADE',
    SALLE_COM = 'SALLE_COM'
}

export enum NavalVesselStatus {
    OPERATIONAL = 'OPERATIONAL',
    IN_MAINTENANCE = 'IN_MAINTENANCE',
    IN_REPAIR = 'IN_REPAIR',
    ON_MISSION = 'ON_MISSION',
    IN_PORT = 'IN_PORT',
    REFITTING = 'REFITTING',
    DECOMMISSIONED = 'DECOMMISSIONED',
    UNAVAILABLE = 'UNAVAILABLE'
}

export enum EscortType {
    STANDARD = 'STANDARD',
    HAUTE_SECURITE = 'HAUTE_SECURITE',
    INTERNATIONALE = 'INTERNATIONALE',
    COTIERE = 'COTIERE',
    HAUTURIERE = 'HAUTURIERE',
    URGENCE = 'URGENCE'
}

export enum ShipStatus {
    IN_PORT = 'IN_PORT',
    AT_SEA = 'AT_SEA',
    UNDER_ESCORT = 'UNDER_ESCORT',
    WAITING = 'WAITING',
    LOADING = 'LOADING',
    UNLOADING = 'UNLOADING',
    IN_MAINTENANCE = 'IN_MAINTENANCE',
    IN_REPAIR = 'IN_REPAIR',
    OTHER = 'OTHER'
}
